# Generated by Django 4.2.5 on 2023-10-13 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Name of the song')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('image', models.ImageField(upload_to='files')),
                ('song', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
